### PR TITLE
Resolve issue #8

### LINKED ISSUE #8: jupyterlab/latex does not work using repo2docker (0.11)
Hi,

there are multiple issues of why the jupyterlab/latex included in this binder example does not work w/ current version of repo2docker:
1. there are annoying compatibility issues between jupterlab and jupyterlab_latex + jupyterlab/latex when using repo2docker,
2. jupyterlab/latex defaults to xetex (already mentioned in https://github.com/binder-examples/latex/pull/5#issuecomment-385772614), 
2. there is a missing figure included in sample.tex.

Note: all these go under point 1. in https://github.com/binder-examples/latex/issues/4#issuecomment-410816460 .

### PR DESCRIPTION
**Pull request by trybik**
Closes #8 

Changes incl:
* use old versions to make repo2docker install jupyterlab/latex extension (I've tried w/ no success also 1.x and 2.x for Python packages)
* default to XeTeX and include missing image for jupyterlab/latex preview to work (manually tested)
* minor cleanups in conda env file: specify explicitly python/pip/setuptools + use pip for installation of pypi packages

### CODE REVIEW

**Comment by choldgraf** [comment]
Hey - thanks for the PR! I don't think that we want the solution to be downgrading jupyterlab to < 1.0...that's a dependency we probably need to keep close to latest. I'm a bit surprised that it doesn't work though - have you asked around in the [jupyter-latex](https://github.com/jupyterlab/jupyterlab-latex) repository? Maybe this is a bug?

**Comment by trybik** [comment]
I fully agree, but no other versions combination would work w/ repo2docker (fails at extension installation step). I didn't ask at jupyter-latex, because I believe this is a [repo2docker](https://github.com/jupyter/repo2docker) (base image / conda) issue rather than jupyter-latex, as I had it working fine w/ jpuyterlab>=1.2,<2.0 in own Docker image.

(Also note that: [jupyter-latex Python requirements for binder](https://github.com/jupyterlab/jupyterlab-latex/blob/master/binder/requirements.txt) are even lower.)

As it seems to be something a bit harder to tackle upstream the toolchain I hoped I could leave it here, at least sharing my discoveries/fixes via this PR.

**Comment by choldgraf** [comment]
hmmm - well if it's a repo2docker issue then we should be able to resolve it with the right config files. All repo2docker is doing is starting with a super minimal base enviornment, and then just installing things on top of it, so we should be able to get wherever we need to that way.

Considering that the jupyter-latex environment is pinned to lab <1.0, perhaps it *only* works with lab <1.0? If that's the case then I'm fine merging this in as-is.

**Comment by trybik** [comment]
I'm positive that `jupyterlab_latex==1.0.0` works with 
`jupyterlab==1.2.6` in `ubuntu:bionic` base image, and I would bet that `jupyterlab_latex>=2.0` works with `jupyterlab>=2.0`, but did not test that myself.

My bet is on issues w/ conda(?) installing first `jupyterlab==1.2.6` which is then uninstalled as you can see in the attached logs, but probably creates some already installed deps issues. There are no logs for lab `>=2.0`, but the error was the same as for `>=1.0,<2.0`. Please note that these logs are from there was still `jupyter lab build` which seems unnecessary.
[JupyterLab<1.0.zip](https://github.com/binder-examples/latex/files/4820554/JupyterLab.1.0.zip)
[JupyterLab>=1.0,<2.0.zip](https://github.com/binder-examples/latex/files/4820555/JupyterLab.1.0.2.0.zip)

**Comment by trybik** [comment]
Some updates:
* same lab build error occurs when using default jupyterlab==1.2.6 as provided by repo2docker (i.e. when not specifying `jupterlab`).
* my bet was wrong: this has something to do w/ the update of the `nodejs`/`npm` toolchain (as used by `jupter/lab/staging` rather than `conda` installing jupyterlab - so IMVHO a jupyterlab issue (not jupterlab-latex or repo2docker one). For ref. attached a build log from running `jupyter labextension install @jupyterlab/latex` in the repo2docker container: 
[jupyterlab-debug-co7idaxq.log](https://github.com/binder-examples/latex/files/4831586/jupyterlab-debug-co7idaxq.log)
    * side note: [someone asked yesterday at SO a very same Q, w/o answer yet](https://stackoverflow.com/questions/62545846/cant-add-extensions-in-jupyterlab-due-to-error-in-build)

**Comment by choldgraf** [comment]
hmmmm - is it worth raising this issue to the attention of the jupyterlab folks then? Unfortunately it means that I am not very well-qualified to debug since I'm not a great javascript person :-/

**Comment by trybik** [comment]
Me neither, but also I was wrong - it is `@jupyterlab/latex` extension issue, jupyterlab builds fine w/o jupyterlab_latex installed via pip
(as an excuse: the JS error was confusing because `module` is a variable where the error comes from, not an actual JS module).

**Comment by choldgraf** [comment]
hmmmm...I am not sure what's the right path forward there :-/

**Comment by trybik** [comment]
I would propose:
1. accept this PR to have a working repo
    * anyway IMVHO the value is in the apt.txt, which is [linked on Binder requirements specs as LaTeX example](https://mybinder.readthedocs.io/en/latest/config_files.html#apt-txt-install-packages-with-apt-get))
2. open "unpin jupyterlab & jupyterlab_latex" issue, and resolve it once the jupyterlab_latex build issues are resolved

The viable alternatively IMVHO is to reject this PR and:
1. remove jupyterlab_latex and fall back on #4, to be resolved once the jupyterlab_latex build issues are resolved
2. fix other, independent, issues from here: the missing figure and extended (improved) apt packages list

**Comment by choldgraf** [comment]
Thanks for the thoughtful explanation - Wanna open up an issue that describes the problem you mentioned above, and then I'll give this a merge?

**Comment by trybik** [comment]
Done: #10

**Comment by choldgraf** [comment]
great - thanks so much for following up on this one 👍

**Pull request merged**
